# metadati
url: https://situas-servizi.istat.it/publish/anagrafica_report_metadato_web?pfun=73&pdata=01/01/2015

"REPORT NAME": "Comuni - Caratteristiche del territorio",
    "REPORT DESCRIZIONE": "L’Istat, ai fini di una descrizione statistica delle caratteristiche geografiche del territorio, diffonde elaborazioni basate sui dati collezionati in occasione delle rilevazioni censuarie o provenienti da altre fonti con riferimento alle principali unità territoriali di interesse per la statistica ufficiale. Pertanto, ai comuni sono assegnati una serie di attributi (grado di urbanizzazione, zone costiere, altimetria, litoraneità, ecoregioni di appartenenza, ecc.) che trovano il loro fondamento su caratteri geo-morfologici o di insediamento urbano, misurati a soli fini statistici.",
    "COL_DETAILS": [
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della Regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "COD_UTS",
            "LABEL": "Codice Provincia/Uts",
            "NOTE": "Codice di tre caratteri alfanumerici con validità nell’intervallo 001-119 per le Province. AI Liberi consorzi restano assegnati i codici delle omonime ex Province (validi nell'intervallo 081-089). Il codice delle Città metropolitane è, invece, creato sommando '200' al codice dell'ex provincia di origine. Infine ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia, cessate secondo le modalità espresse con L.r. 20/2016.",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia o Unità territoriale sovracomunale (Uts). Le Unità territoriali sovracomunali, definite a fini statistici, ricomprendono dal 2015 oltre alle Province anche le Città metropolitane, i Liberi consorzi e le unità non amministrative (ex Province del Friuli-Venezia Giulia), al fine di costituire una suddivisione completa del territorio nazionale.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "COD_PROV_STORICO",
            "LABEL": "Codice Provincia (Storico)",
            "NOTE": "A partire dal 1/1/2015 con l'entrata in vigore delle Città metropolitane i codici delle province corrispondenti permangono al solo scopo di costituire il codice del Comune, che non subisce variazioni. Allo stesso scopo, e ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia (l.r. 20/2016)",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia vigente o cessata (tre caratteri, formato alfanumerico con validità nell’intervallo 001-119)",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "PRO_COM_T",
            "LABEL": "Codice Comune (alfanumerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato alfanumerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "PRO_COM",
            "LABEL": "Codice comune (numerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato numerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "COMUNE",
            "LABEL": "Comune",
            "NOTE": "La denominazione ufficiale dei comuni della Provincia di Bolzano/Bozen e di alcuni comuni del Friuli-Venezia Giulia è definita dall'associazione del nome italiano a quello straniero. Per le denominazioni bilingue è previsto l'uso del simbolo separatore: \"/\" per i comuni della Provincia di Bolzano/Bozen, e \"-\" per tutti gli altri.",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua italiana e straniera",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "COMUNE_A",
            "LABEL": "Comune (dizione straniera)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua diversa dall'italiano",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "SIGLA_AUTOMOBILISTICA",
            "LABEL": "Sigla automobilistica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Sigla automobilistica della provincia, e dal 2015 della città metropolitana, libero consorzio o unità non amministrativa (ex province del Friuli-Venezia Giulia). Null quando non disponibile",
            "FORMATMASK": "",
            "FONTE": "Motorizzazione",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "COM_ISO",
            "LABEL": "Comune isolano",
            "NOTE": "Comuni appartenenti alle isole marittime minori e lacuali. Il comune di Sant'Antioco (provincia Sud Sardegna) risulta avere più di una sezione ricadente nell'Isola maggiore, mentre il comune isolano di Monte Isola (BS) è l'unico classificabile come lacuale.",
            "LINK": "",
            "GUIDA": "1=Comune isolano; 0=Comune non isolano; null quando non disponibile.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "COM_LIT",
            "LABEL": "Comune litoraneo",
            "NOTE": "Il comune che ha almeno un tratto del proprio confine bagnato dal mare. Sono esclusi da tale categoria i cosiddetti comuni lacuali, i cui confini sono interessati dagli specchi d’acqua interni (laghi).",
            "LINK": "",
            "GUIDA": "1=Comune litoraneo; 0=Comune non litoraneo; null quando non disponibile.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "ZONA_ALT",
            "LABEL": "Zona altimetrica",
            "NOTE": "Ripartizione del territorio nazionale in zone omogenee derivanti dall'aggregazione di comuni contigui sulla base di valori soglia altimetrici.",
            "LINK": "https://ebiblio.istat.it/digibib/Metodi%20e%20norme/SBL0493189MeN_SerieC1_Circoscrizioni_statistiche.pdf",
            "GUIDA": "1=Montagna interna; 2=Montagna litoranea; 3=Collina interna; 4=Collina litoranea; 5=Pianura; Null quando non disponibile.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "ZONE_COST_2011",
            "LABEL": "Zone costiere 2011",
            "NOTE": "Classificazione dei comuni secondo il grado di vicinanza dalla costa, elaborata su dati Istat, concordata con Eurostat ed armonizzata a livello europeo nel 2018 a seguito dell'adozione del Regolamento (UE) 2017/2391 del Parlamento Europeo e del Consiglio (Tercet) e del Regolamento di esecuzione (UE) 2019/1130 sulle tipologie territoriali europee. Per permettere l'analisi diacronica di statistiche e indicatori a livello comunale, l'Istat ha predisposto una elaborazione geografica che, sulla base del limite esterno delle sezioni litoranee delle basi territoriali  2011integrato con le sezioni che includono corpi d’acqua (lagune e stagni litoranei) e utilizzando i medesimi criteri di soglia sulla superficie previsti dal Regolamento Tercet, assegna la classificazione anche ai comuni cessati prima del 2018 ed esistenti dal 2008. Ai comuni situati sulla costa o aventi almeno il 50 % della superficie a una distanza dal mare inferiore a 10 km, sono aggiunte le  enclave (comuni non costieri circondati da comuni costieri adiacenti).",
            "LINK": "",
            "GUIDA": "1= Zone costiere, comuni situati sulla costa o avente almeno il 50 % della superficie a una distanza dal mare inferiore a 10 km; 0= Zone non costiere; Null quando non disponibile.",
            "FORMATMASK": "",
            "FONTE": "",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "DEGURBA_2011",
            "LABEL": "Degurba 2011",
            "NOTE": "Il grado di urbanizzazione (Degree of Urbanisation - DEGURBA) dei comuni è una classificazione armonizzata introdotta da Eurostat  basata sul criterio della contiguità geografica e su soglie di popolazione minima della griglia regolare con celle da 1 km2 (Geostat grid). Questa versione della classificazione è basata sulla griglia di popolazione rilasciata per il Censimento della popolazione 2011. A seguito dell’adozione del Regolamento Tercet  del Parlamento Europeo e del Consiglio (Reg. (UE) 2017/2391), del Regolamento di esecuzione (UE) 2019/1130 e della pubblicazione della metodologia da parte di Eurostat, Istat ha rilasciato, nel 2018, i valori della classificazione per i comuni italiani ricostruendoli a partire dal 9 ottobre 2011.",
            "LINK": "",
            "GUIDA": "1 = Città o Zone densamente popolate; 2 = Piccole città e sobborghi o Zone a densità intermedia di popolazione; 3 = Zone rurali o Zone scarsamente popolate; Null quando non disponibile.\r\nBasata su Geostat grid 2011.",
            "FORMATMASK": "",
            "FONTE": "Eurostat e Istat",
            "TYPE": "NUMBER"
        }
    ]
}

In [1]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [6]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase
import Modulo_Fase_02 as pd_fase1

In [7]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Modulo_Common as pd_common

In [10]:
df_comuni = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Comune_All.csv")

In [11]:
df_comuni.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_UTS,COD_PROV_STORICO,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,...,DEN_ECO_DIV_2018,COD_ECO_PRO_2018,DEN_ECO_PRO_2018,COD_ECO_SEZ_2018,DEN_ECO_SEZ_2018,COD_ECO_SSEZ_2018,DEN_ECO_SSEZ_2018,ALT,ZONE_COST_2021,DEGURBA_2021
0,0,0,1,1,201,1,1001,1001,Agliè,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,1,201,1,1002,1002,Airasca,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,1,1,201,1,1003,1003,Ala di Stura,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,1,1,201,1,1004,1004,Albiano d'Ivrea,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,1,1,201,1,1005,1005,Alice Superiore,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_comuni.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'COD_UTS',
       'COD_PROV_STORICO', 'PRO_COM_T', 'PRO_COM', 'COMUNE', 'COMUNE_A',
       'SIGLA_AUTOMOBILISTICA', 'COM_ISO', 'COM_LIT', 'ZONA_ALT',
       'ZONE_COST_2011', 'DEGURBA_2011', 'anno_riferimento',
       'COD_ECO_DIV_2018', 'DEN_ECO_DIV_2018', 'COD_ECO_PRO_2018',
       'DEN_ECO_PRO_2018', 'COD_ECO_SEZ_2018', 'DEN_ECO_SEZ_2018',
       'COD_ECO_SSEZ_2018', 'DEN_ECO_SSEZ_2018', 'ALT', 'ZONE_COST_2021',
       'DEGURBA_2021'],
      dtype='str')

In [13]:
df_comuni.info

<bound method DataFrame.info of        Unnamed: 0.1  Unnamed: 0  COD_RIP  COD_REG  COD_UTS  COD_PROV_STORICO  \
0                 0           0        1        1      201                 1
1                 1           1        1        1      201                 1
2                 2           2        1        1      201                 1
3                 3           3        1        1      201                 1
4                 4           4        1        1      201                 1
...             ...         ...      ...      ...      ...               ...
87322          7891        7891        5       20      111               111
87323          7892        7892        5       20      111               111
87324          7893        7893        5       20      111               111
87325          7894        7894        5       20      111               111
87326          7895        7895        5       20      111               111

       PRO_COM_T  PRO_COM           COMUNE COMUNE_A  ...  \
0           1001     1001            Agliè      NaN  ...
1           1002     1002          Airasca      NaN  ...
2           1003     1003     Ala di Stura      NaN  ...
3           1004     1004  Albiano d'Ivrea      NaN  ...
4           1005     1005  Alice Superiore      NaN  ...
...          ...      ...              ...      ...  ...
87322     111103   111103       Villaputzu      NaN  ...
87323     111104   111104       Villasalto      NaN  ...
87324     111105   111105      Villasimius      NaN  ...
87325     111106   111106         Villasor      NaN  ...
87326     111107   111107    Villaspeciosa      NaN  ...

             DEN_ECO_DIV_2018  COD_ECO_PRO_2018     DEN_ECO_PRO_2018  \
0                         NaN               NaN                  NaN
1                         NaN               NaN                  NaN
2                         NaN               NaN                  NaN
3                         NaN               NaN                  NaN
4                         NaN               NaN                  NaN
...                       ...               ...                  ...
87322  Divisione Mediterranea                2B  Provincia Tirrenica
87323  Divisione Mediterranea                2B  Provincia Tirrenica
87324  Divisione Mediterranea                2B  Provincia Tirrenica
87325  Divisione Mediterranea                2B  Provincia Tirrenica
87326  Divisione Mediterranea                2B  Provincia Tirrenica

       COD_ECO_SEZ_2018  DEN_ECO_SEZ_2018  COD_ECO_SSEZ_2018  \
0                   NaN               NaN                NaN
1                   NaN               NaN                NaN
2                   NaN               NaN                NaN
3                   NaN               NaN                NaN
4                   NaN               NaN                NaN
...                 ...               ...                ...
87322               2B4     Sezione Sarda               2B4c
87323               2B4     Sezione Sarda               2B4c
87324               2B4     Sezione Sarda               2B4c
87325               2B4     Sezione Sarda               2B4a
87326               2B4     Sezione Sarda               2B4a

                        DEN_ECO_SSEZ_2018    ALT ZONE_COST_2021 DEGURBA_2021
0                                     NaN    NaN            NaN          NaN
1                                     NaN    NaN            NaN          NaN
2                                     NaN    NaN            NaN          NaN
3                                     NaN    NaN            NaN          NaN
4                                     NaN    NaN            NaN          NaN
...                                   ...    ...            ...          ...
87322    Sottosezione Sarda Sud-Orientale    8.0            1.0          3.0
87323    Sottosezione Sarda Sud-Orientale  506.0            0.0          3.0
87324    Sottosezione Sarda Sud-Orientale   49.0            1.0          3.0
87325  Sottosezione Sarda Sud-Occidentale   24.0            0.0          2.0
87326  Sottosezione Sarda Sud-Occidentale   13.0            0.0          3.0

[87327 rows x 28 columns]>

In [14]:
#LAVORO SU UN DATASET DI LAVORO DIFFERENTE DALLA SORGENTE
df_comuni_EDA = df_comuni.copy()

In [15]:
df_comuni_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_UTS,COD_PROV_STORICO,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,...,DEN_ECO_DIV_2018,COD_ECO_PRO_2018,DEN_ECO_PRO_2018,COD_ECO_SEZ_2018,DEN_ECO_SEZ_2018,COD_ECO_SSEZ_2018,DEN_ECO_SSEZ_2018,ALT,ZONE_COST_2021,DEGURBA_2021
0,0,0,1,1,201,1,1001,1001,Agliè,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,1,201,1,1002,1002,Airasca,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Colonne di interesse:

        {
            "COLNAME": "COD_UTS",
            "LABEL": "Codice Provincia/Uts",
            "NOTE": "Codice di tre caratteri alfanumerici con validità nell’intervallo 001-119 per le Province. AI Liberi consorzi restano assegnati i codici delle omonime ex Province (validi nell'intervallo 081-089). Il codice delle Città metropolitane è, invece, creato sommando '200' al codice dell'ex provincia di origine. Infine ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia, cessate secondo le modalità espresse con L.r. 20/2016.",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia o Unità territoriale sovracomunale (Uts). Le Unità territoriali sovracomunali, definite a fini statistici, ricomprendono dal 2015 oltre alle Province anche le Città metropolitane, i Liberi consorzi e le unità non amministrative (ex Province del Friuli-Venezia Giulia), al fine di costituire una suddivisione completa del territorio nazionale.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

        {
            "COLNAME": "COMUNE",
            "LABEL": "Comune",
            "NOTE": "La denominazione ufficiale dei comuni della Provincia di Bolzano/Bozen e di alcuni comuni del Friuli-Venezia Giulia è definita dall'associazione del nome italiano a quello straniero. Per le denominazioni bilingue è previsto l'uso del simbolo separatore: \"/\" per i comuni della Provincia di Bolzano/Bozen, e \"-\" per tutti gli altri.",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua italiana e straniera",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

        {
            "COLNAME": "PRO_COM",
            "LABEL": "Codice comune (numerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato numerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della Regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

         {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

In [16]:
# MI CONSERVO SOLO LE COLONNE CHE HO INDICATO DI INTERESSE
df_comuni_EDA = df_comuni_EDA[['COD_RIP', 'COD_REG', 'COD_UTS',
       'PRO_COM', 'COMUNE']]

In [17]:
#VERIFICO ALCUNE INFO
df_comuni_EDA['COD_RIP'].unique()

array([1, 2, 3, 4, 5])

In [18]:
df_comuni_EDA[df_comuni_EDA['COD_RIP']==1].head(5)

   COD_RIP  COD_REG  COD_UTS  PRO_COM           COMUNE
0        1        1      201     1001            Agliè
1        1        1      201     1002          Airasca
2        1        1      201     1003     Ala di Stura
3        1        1      201     1004  Albiano d'Ivrea
4        1        1      201     1005  Alice Superiore

In [19]:
df_comuni_EDA['COD_REG'].unique()

array([ 1,  2,  7,  3,  4,  5,  6,  8, 11,  9, 10, 12, 15, 13, 14, 16, 17,
       18, 19, 20])

In [21]:
df_comuni_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 87327 entries, 0 to 87326
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COD_RIP  87327 non-null  int64
 1   COD_REG  87327 non-null  int64
 2   COD_UTS  87327 non-null  int64
 3   PRO_COM  87327 non-null  int64
 4   COMUNE   87316 non-null  str
dtypes: int64(4), str(1)
memory usage: 3.3 MB

In [ ]:
# a) tipo dato corretto
# b) non sono presenti colonne nulle

In [22]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_comuni_EDA, f"ElencoComuni",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv
      Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv' non esiste
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv