# metadati
metadati del documento:

{
    "REPORT NAME": "Elenco Regioni",
    "REPORT DESCRIZIONE": "Il report restituisce la lista delle regioni vigenti alla data selezionata e le loro principali caratteristiche o classificazioni statistico-amministrative disponibili.",
    "COL_DETAILS": [
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "DEN_REG",
            "LABEL": "Regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

non la prendo 
    {
            "COLNAME": "TIPO_REG",
            "LABEL": "Flag tipo regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Descrizione Ente: 1= Regione a Statuto ordinario; 2=Regione a Statuto speciale",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
non la prendo 
        {
            "COLNAME": "DESC_TIPO_REG",
            "LABEL": "Tipo regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Regione a statuto ordinario o Regione a statuto speciale",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

non la prendo 
        {
            "COLNAME": "DEN_RIP",
            "LABEL": "Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della ripartizione geografica  secondo la suddivisione del territorio nazionale in 5 ambiti: Nord-ovest, Nord-est, Centro, Sud e Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        
non la prendo 
        {
            "COLNAME": "COD_REG_FISCALE",
            "LABEL": "Codice fiscale",
            "NOTE": "Codice di 11 caratteri in formato testo",
            "LINK": "",
            "GUIDA": "Codice attribuito dall’Agenzia delle Entrate al fine di identificare in modo univoco un soggetto giuridico",
            "FORMATMASK": "",
            "FONTE": "Agenzia delle Entrate",
            "TYPE": "VARCHAR"
        },

non la prendo 
        {
            "COLNAME": "COD_NUTS2_2010",
            "LABEL": "Codice NUTS2 2010",
            "NOTE": "Cfr. Regolamenti (UE) della Commissione n. 31/2011, n. 1319/2013 e n. 2066/2016. Nella nomenclatura NUTS non è presente la regione di livello 2 \"Trentino-Alto Adige/Südtirol\", al suo posto compaiono la \"Provincia autonoma di Bolzano/Bozen\" (ITH1) e la \"Provincia autonoma di Trento\" (ITH2).",
            "LINK": "https://ec.europa.eu/eurostat/web/nuts/history",
            "GUIDA": "Nomenclatura delle unità territoriali europee (NUTS2) corrispondente al livello territoriale delle regioni, valida dal 2010 al 2020",
            "FORMATMASK": "",
            "FONTE": "Eurostat",
            "TYPE": "VARCHAR"
        }
    ]
}

In [2]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [3]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Modulo_Common as pd_common

In [4]:
df_regioni = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Regione_All.csv")

In [5]:
df_regioni.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,DEN_REG,DEN_RIP,TIPO_REG,DESC_TIPO_REG,COD_REG_FISCALE,COD_NUTS2_2010,anno_riferimento,COD_NUTS2_2021,COD_NUTS2_2024
0,0,0,1,1,Piemonte,Nord-ovest,1,Regione a Statuto ordinario,80087670016,ITC1,2015,NaN,NaN
1,1,1,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest,2,Regione a Statuto speciale,80002270074,ITC2,2015,NaN,NaN
2,2,2,1,3,Lombardia,Nord-ovest,1,Regione a Statuto ordinario,80050050154,ITC4,2015,NaN,NaN
3,3,3,2,4,Trentino-Alto Adige/Südtirol,Nord-est,2,Regione a Statuto speciale,80003690221,NaN,2015,NaN,NaN
4,4,4,2,5,Veneto,Nord-est,1,Regione a Statuto ordinario,80007580279,ITH3,2015,NaN,NaN

In [6]:
df_regioni.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'DEN_REG',
       'DEN_RIP', 'TIPO_REG', 'DESC_TIPO_REG', 'COD_REG_FISCALE',
       'COD_NUTS2_2010', 'anno_riferimento', 'COD_NUTS2_2021',
       'COD_NUTS2_2024'],
      dtype='str')

In [7]:
df_regioni_EDA = df_regioni.copy()

In [8]:
df_regioni_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,DEN_REG,DEN_RIP,TIPO_REG,DESC_TIPO_REG,COD_REG_FISCALE,COD_NUTS2_2010,anno_riferimento,COD_NUTS2_2021,COD_NUTS2_2024
0,0,0,1,1,Piemonte,Nord-ovest,1,Regione a Statuto ordinario,80087670016,ITC1,2015,NaN,NaN
1,1,1,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest,2,Regione a Statuto speciale,80002270074,ITC2,2015,NaN,NaN

In [11]:
# come indicato nella prima sezione, mi tengo le colonne di interesse
df_regioni_EDA = df_regioni_EDA[['anno_riferimento','COD_RIP', 'COD_REG', 'DEN_REG' ]]

In [12]:
df_regioni_EDA['COD_RIP'].unique()

array([1, 2, 3, 4, 5])

In [13]:
df_regioni_EDA['COD_REG'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
df_regioni_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  220 non-null    int64
 1   COD_RIP           220 non-null    int64
 2   COD_REG           220 non-null    int64
 3   DEN_REG           220 non-null    str
dtypes: int64(3), str(1)
memory usage: 7.0 KB

In [ ]:
# a) tipo dato corretto
# b) non sono presenti colonne nulle

In [16]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_regioni_EDA, f"ElencoRegioni",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv
      Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv' non esiste
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv