# metadati
metadati del documento:

metadati del documento:

{
    "REPORT NAME": "Elenco Province/Uts",
    "REPORT DESCRIZIONE": "Il report restituisce la lista delle province o unità territoriali sovracomunali (Uts) vigenti alla data selezionata e le loro principali caratteristiche o classificazioni statistico-amministrative disponibili. Ogni unità territoriale è identificata dalla denominazione e dal codice statistico.",
    "COL_DETAILS": [

    non mi serve, presa da regioni
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

    si
        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della Regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "COD_PROV_STORICO",
            "LABEL": "Codice Provincia (storico)",
            "NOTE": "A partire dal 1/1/2015 con l'entrata in vigore delle Città metropolitane i codici delle Province corrispondenti permangono al solo scopo di costituire il codice del comune, che non subisce variazioni. Allo stesso scopo, e ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia (l.r. 20/2016)",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia vigente o cessata (tre caratteri, formato alfanumerico con validità nell’intervallo 001-119)",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    si
        {
            "COLNAME": "COD_UTS",
            "LABEL": "Codice Provincia/Uts",
            "NOTE": "Codice di tre caratteri alfanumerici con validità nell’intervallo 001-119 per le Province. Restano assegnati ai Liberi consorzi i codici delle omonime ex Province (validi nell'intervallo 081-089). Il codice delle Città metropolitane è, invece, creato sommando '200' al codice della provincia corrispondente. Ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia, cessate secondo le modalità espresse con Legge regionale 20/2016.",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia o Unità territoriale sovracomunale (Uts). Le Unità territoriali sovracomunali, definite a fini statistici, ricomprendono, a partire dal 2015, oltre le Province anche le Città metropolitane, i Liberi consorzi e le unità non amministrative (ex Province del Friuli-Venezia Giulia).",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "DEN_UTS",
            "LABEL": "Provincia/Uts",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della Provincia o Unità territoriale sovracomunale (Uts).",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo --> region
        {
            "COLNAME": "DEN_RIP",
            "LABEL": "Ripartizione geografica",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Denominazione della ripartizione geografica  secondo la suddivisione del territorio nazionale in 5 ambiti: Nord-ovest, Nord-est, Centro, Sud e Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "DEN_REG",
            "LABEL": "Regione",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Denominazione della Regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "TIPO_UTS",
            "LABEL": "Tipologia Provincia/Uts",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Tipologia dell'Unità territoriale sovracomunale (Uts): 1=Provincia; 2=Provincia autonoma; 3=Città metropolitana; 4=Libero consorzio di comuni; 5=Unità non amministrativa (ex- province del Friuli-Venezia Giulia)",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

    non la prendo
        {
            "COLNAME": "DESC_TIPO_UTS",
            "LABEL": "Descrizione tipologia Provincia/Uts",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Descrizione della tipologia di Unità territoriale sovracomunale (Uts): Provincia; Provincia autonoma; Città metropolitana; Libero consorzio di comuni; Unità non amministrativa (ex- province del Friuli-Venezia Giulia)",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "SIGLA_AUTOMOBILISTICA",
            "LABEL": "Sigla automobilistica",
            "NOTE": "",
            "LINK": "",
            "GUIDA": "Sigla automobilistica della Provincia, e dal 2015 della Città metropolitana, libero consorzio o unità non amministrativa (ex Province del Friuli-Venezia Giulia). Null quando non disponibile",
            "FORMATMASK": "",
            "FONTE": "Motorizzazione",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "COD_PROV_FISCALE",
            "LABEL": "Codice fiscale",
            "NOTE": "Codice di 11 caratteri in formato testo",
            "LINK": "",
            "GUIDA": "Codice attribuito dall’Agenzia delle Entrate al fine di identificare in modo univoco un soggetto giuridico",
            "FORMATMASK": "",
            "FONTE": "Agenzia delle entrate",
            "TYPE": "VARCHAR"
        },

    non la prendo
        {
            "COLNAME": "COD_NUTS3_2024",
            "LABEL": "Codice NUTS3 2024",
            "NOTE": "Cfr. Commission Delegated Regulation 2023/674",
            "LINK": "https://ec.europa.eu/eurostat/web/nuts/history",
            "GUIDA": "Nomenclatura delle unità territoriali europee (NUTS3) corrispondente al livello territoriale delle Province/Citta metropolitane (Uts-Unità territoriali sovracomunali), valida dal 2024 con il cambio denominazione della Nuts3 Reggio di Calabria in Reggio Calabria, fino al 2026. La Nomenclatura Nuts3 versione 2024 non include la classificazione delle Province sarde \"Gallura Nord-Est Sardegna, \"Ogliastra\", \"Sulcis Iglesiente\" e \"Medio Campidano\" e la Città metropolitana di Sassari, istituite nel 2025.",
            "FORMATMASK": "",
            "FONTE": "Eurostat",
            "TYPE": "VARCHAR"
        }
    ]
}

In [3]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [1]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune

#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [4]:
df_province = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Province_All.csv")

In [5]:
df_province.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_PROV_STORICO,COD_UTS,DEN_UTS,DEN_RIP,DEN_REG,TIPO_UTS,DESC_TIPO_UTS,SIGLA_AUTOMOBILISTICA,COD_PROV_FISCALE,COD_NUTS3_2010,anno_riferimento,COD_NUTS3_2021,COD_NUTS3_2024
0,0,0,1,1,2,2,Vercelli,Nord-ovest,Piemonte,1,Provincia,VC,80005210028,ITC12,2015,NaN,NaN
1,1,1,1,1,3,3,Novara,Nord-ovest,Piemonte,1,Provincia,NO,80026850034,ITC15,2015,NaN,NaN
2,2,2,1,1,4,4,Cuneo,Nord-ovest,Piemonte,1,Provincia,CN,447820044,ITC16,2015,NaN,NaN
3,3,3,1,1,5,5,Asti,Nord-ovest,Piemonte,1,Provincia,AT,80001630054,ITC17,2015,NaN,NaN
4,4,4,1,1,6,6,Alessandria,Nord-ovest,Piemonte,1,Provincia,AL,80003870062,ITC18,2015,NaN,NaN

In [6]:
df_province.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'COD_PROV_STORICO',
       'COD_UTS', 'DEN_UTS', 'DEN_RIP', 'DEN_REG', 'TIPO_UTS', 'DESC_TIPO_UTS',
       'SIGLA_AUTOMOBILISTICA', 'COD_PROV_FISCALE', 'COD_NUTS3_2010',
       'anno_riferimento', 'COD_NUTS3_2021', 'COD_NUTS3_2024'],
      dtype='str')

In [7]:
df_province_EDA = df_province.copy()

In [8]:
df_province_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_PROV_STORICO,COD_UTS,DEN_UTS,DEN_RIP,DEN_REG,TIPO_UTS,DESC_TIPO_UTS,SIGLA_AUTOMOBILISTICA,COD_PROV_FISCALE,COD_NUTS3_2010,anno_riferimento,COD_NUTS3_2021,COD_NUTS3_2024
0,0,0,1,1,2,2,Vercelli,Nord-ovest,Piemonte,1,Provincia,VC,80005210028,ITC12,2015,NaN,NaN
1,1,1,1,1,3,3,Novara,Nord-ovest,Piemonte,1,Provincia,NO,80026850034,ITC15,2015,NaN,NaN

In [9]:
df_province_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 1293 entries, 0 to 1292
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           1293 non-null   int64
 1   Unnamed: 0             1293 non-null   int64
 2   COD_RIP                1293 non-null   int64
 3   COD_REG                1293 non-null   int64
 4   COD_PROV_STORICO       1293 non-null   int64
 5   COD_UTS                1293 non-null   int64
 6   DEN_UTS                1293 non-null   str
 7   DEN_RIP                1293 non-null   str
 8   DEN_REG                1293 non-null   str
 9   TIPO_UTS               1293 non-null   int64
 10  DESC_TIPO_UTS          1293 non-null   str
 11  SIGLA_AUTOMOBILISTICA  1281 non-null   str
 12  COD_PROV_FISCALE       1293 non-null   int64
 13  COD_NUTS3_2010         640 non-null    str
 14  anno_riferimento       1293 non-null   int64
 15  COD_NUTS3_2021         321 non-null    str
 16  COD_NUTS3_2024         319 non-null    str
dtypes: int64(9), str(8)
memory usage: 171.9 KB

In [10]:
# come indicato nella prima sezione, mi tengo le colonne di interesse
df_province_EDA = df_province_EDA[['anno_riferimento', 'COD_REG', 'COD_UTS','DEN_UTS' ]]

In [11]:
df_province_EDA['COD_UTS'].unique()

array([  2,   3,   4,   5,   6,  96, 103, 201,   7,  12,  13,  14,  16,
        17,  18,  19,  20,  97,  98, 108, 215,  21,  22,  23,  24,  25,
        26,  28,  29, 227,  30,  31,  32,  93,   8,   9,  11, 210,  33,
        34,  35,  36,  38,  39,  40,  99, 237,  45,  46,  47,  49,  50,
        51,  52,  53, 100, 248,  54,  55,  41,  42,  43,  44, 109,  56,
        57,  59,  60, 258,  66,  67,  68,  69,  70,  94,  61,  62,  64,
        65, 263,  71,  73,  74,  75, 110, 272,  76,  77,  78,  79,  80,
       101, 102,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  95, 104, 105, 106, 107, 280, 282, 283, 287, 111, 292, 113,
       114, 115, 116, 117, 119, 312, 318])

In [12]:
df_province_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 1293 entries, 0 to 1292
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  1293 non-null   int64
 1   COD_REG           1293 non-null   int64
 2   COD_UTS           1293 non-null   int64
 3   DEN_UTS           1293 non-null   str
dtypes: int64(3), str(1)
memory usage: 40.5 KB

In [ ]:
# a) tipo dato corretto
# b) non sono presenti colonne nulle

In [13]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_province_EDA, f"ElencoProvince",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoProvince.csv
      Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoProvince.csv' non esiste
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoProvince.csv