# metadati
preso dal link indicato in file 01_b


       {
    "REPORT NAME": "Comuni - Dimensione",
    "REPORT DESCRIZIONE": "Il report restituisce la lista dei comuni esistenti alla data selezionata e la relativa dimensione in termini di ampiezza demografica (popolazione residente e legale) e di estensione territoriale (superficie in kmq). Ogni unità è identificata dalla denominazione e dal codice statistico. Il dato sulla popolazione legale viene reso disponibile a partire dal IX Censimento generale della popolazione (4 novembre 1951), quello sulla popolazione residente dal 31 dicembre 2001 mentre la superficie territoriale a partire dal XIV Censimento generale della popolazione e delle abitazioni (21 ottobre 2001).",
    "COL_DETAILS": [

si ma sarà presa dalla regione
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della Ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

si
        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della Regione.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },


no
        {
            "COLNAME": "COD_PROV_STORICO",
            "LABEL": "Codice Provincia (Storico)",
            "NOTE": "A partire dal 1/1/2015 con l'entrata in vigore delle Città metropolitane i codici delle Province corrispondenti permangono al solo scopo di costituire il codice del Comune, che non subisce variazioni. Allo stesso scopo, e ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia (l.r. 20/2016)",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia vigente o cessata (tre caratteri, formato alfanumerico con validità nell’intervallo 001-119)",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

si incerto
        {
            "COLNAME": "COD_UTS",
            "LABEL": "Codice Provincia/Uts",
            "NOTE": "Codice di tre caratteri alfanumerici con validità nell’intervallo 001-119 per le Province. Restano assegnati ai Liberi consorzi i codici delle omonime ex Province (validi nell'intervallo 081-089). Il codice delle Città metropolitane è, invece, creato sommando '200' al codice della Provincia corrispondente. Ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia, cessate secondo le modalità espresse con Legge regionale 20/2016.",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia o Unità territoriale sovracomunale (Uts). Le unità territoriali sovracomunali, definite a fini statistici, ricomprendono, a partire dal 2015, oltre le Province anche le Città metropolitane, i Liberi consorzi e le unità non amministrative (ex Province del Friuli-Venezia Giulia).",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

no
        {            
            "COLNAME": "PRO_COM_T",
            "LABEL": "Codice Comune (alfanumerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato alfanumerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

si
        {
            "COLNAME": "PRO_COM",
            "LABEL": "Codice Comune (numerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato numerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

si
        {
            "COLNAME": "COMUNE",
            "LABEL": "Comune",
            "NOTE": "La denominazione ufficiale dei comuni della Provincia di Bolzano/Bozen e di alcuni comuni dell Friuli-Venezia Giulia è definita dall'associazione del nome italiano a quello straniero. Per le denominazioni bilingue è previsto l'uso del simbolo separatore: \"/\" per i comuni della Provincia di Bolzano/Bozen, e \"-\" per tutti gli altri.",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua italiana e straniera",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

no
        {
            "COLNAME": "COMUNE_A",
            "LABEL": "Comune (dizione straniera)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua diversa dall'italiano",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

no
        {
            "COLNAME": "SIGLA_AUTOMOBILISTICA",
            "LABEL": "Sigla automobilistica",
            "NOTE": "Note non presenti",
            "LINK": " ",
            "GUIDA": "Sigla automobilistica della Provincia, e dal 2015 della Città metropolitana, Libero consorzio o unità non amministrativa.",
            "FORMATMASK": "",
            "FONTE": "Motorizzazione",
            "TYPE": "VARCHAR"
        },

no prendo pop_res
        {
            "COLNAME": "POP_LEG",
            "LABEL": "Popolazione legale",
            "NOTE": "Per i comuni istituiti o interessati rispettivamente da processi di fusione o incorporazione di comuni soppressi, la popolazione alla data del  Censimento generale della popolazione è ricostruita per somma. Per i comuni interessati da eventi di cessioni e/o acquisizioni di porzioni di territorio la popolazione legale è ricostruita secondo i dati trasmessi dai Comuni interessati.",
            "LINK": " ",
            "GUIDA": "Popolazione residente legale alla data del Censimento di riferimento determinata con Decreto del Presidente della Repubblica.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

no

        {
            "COLNAME": "ANNO_CENSIMENTO",
            "LABEL": "Anno Censimento",
            "NOTE": "Note non presenti",
            "LINK": " ",
            "GUIDA": "Anno di riferimento dei dati",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

si
        {
            "COLNAME": "AREA_KMQ",
            "LABEL": "Superficie (Kmq)",
            "NOTE": "I dati, rilasciati ai soli fini statistici, sono diffusi annualmente, a partire dal 2002 con riferimenti al 1° gennaio.\r\nFanno eccezione gli anni censuari 2001 e 2011, riferiti rispettivamente al 21 ottobre e al 9 ottobre, e l'anno 2021, riferito al 31 dicembre.\"\r\nSuccessivamente a tali date, in caso di eventi di fusione o incorporazione, la superficie è ricostruita per somma. Resta invece invariata la superficie dei Comuni interessati da cessioni o acquisizioni di singole porzioni di territorio",
            "LINK": "https://www.istat.it/notizia/confini-delle-unita-amministrative-a-fini-statistici-al-1-gennaio-2018-2/",
            "GUIDA": "Superficie comunale espressa in kmq ricavata dallo strato geografico dei limiti comunali tramite il sistema informativo geografico (GIS) in uso presso l’Istat. Il dato può subire variazioni annuali dovute agli arrotondamenti nel calcolo o all'aggiornamento della base censuaria di riferimento.",
            "FORMATMASK": "",
            "FONTE": "Istat-Basi territoriali, Confini delle unità amministrative a fini statistici (shapefile - versione non generalizzata)",
            "TYPE": "VARCHAR"
        },

no
        {
            "COLNAME": "ANNO_AREA",
            "LABEL": "Anno (Superficie)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Anno di riferimento dei dati",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

si
        {
            "COLNAME": "POP_RES",
            "LABEL": "Popolazione residente",
            "NOTE": "Successivamente al 31 dicembre dell'anno di riferimento, per i Comuni istituiti mediante fusione o in caso di incorporazione di comuni soppressi, la popolazione è ricostruita per somma. Resta invariata la popolazione dei Comuni con eventi di cessioni e/o acquisizioni di porzioni di territorio.",
            "LINK": "https://demo.istat.it/",
            "GUIDA": "Elaborazione della popolazione residente al 31 dicembre dell'anno di riferimento. Movimento e calcolo della popolazione residente annuale.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

no
        {
            "COLNAME": "ANNO_POP_RES",
            "LABEL": "Anno (Popolazione residente)",
            "NOTE": "Note non presenti",
            "LINK": " ",
            "GUIDA": "Anno di riferimento dei dati",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        }
    ]
}

In [4]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [ ]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

#import Moduli.Modulo_Fase_02 as pd_fase1

In [ ]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Moduli.Modulo_Common as pd_common

In [7]:
df_comuni = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Comune_All.csv")

In [8]:
df_comuni.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_PROV_STORICO,COD_UTS,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,SIGLA_AUTOMOBILISTICA,POP_LEG,ANNO_CENSIMENTO,AREA_KMQ,ANNO_AREA,POP_RES,ANNO_POP_RES,anno_riferimento
0,0,0,1,1,1,201,1001,1001,Agliè,NaN,TO,2644,2011,"13,1462",2015,2701,2014,2015
1,1,1,1,1,1,201,1002,1002,Airasca,NaN,TO,3819,2011,"15,7393",2015,3798,2014,2015
2,2,2,1,1,1,201,1003,1003,Ala di Stura,NaN,TO,462,2011,"46,3315",2015,465,2014,2015
3,3,3,1,1,1,201,1004,1004,Albiano d'Ivrea,NaN,TO,1791,2011,"11,7314",2015,1754,2014,2015
4,4,4,1,1,1,201,1005,1005,Alice Superiore,NaN,TO,701,2011,"7,3796",2015,717,2014,2015

In [9]:
df_comuni.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'COD_PROV_STORICO',
       'COD_UTS', 'PRO_COM_T', 'PRO_COM', 'COMUNE', 'COMUNE_A',
       'SIGLA_AUTOMOBILISTICA', 'POP_LEG', 'ANNO_CENSIMENTO', 'AREA_KMQ',
       'ANNO_AREA', 'POP_RES', 'ANNO_POP_RES', 'anno_riferimento'],
      dtype='str')

In [10]:
df_comuni.info()

<class 'pandas.DataFrame'>
RangeIndex: 87327 entries, 0 to 87326
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           87327 non-null  int64
 1   Unnamed: 0             87327 non-null  int64
 2   COD_RIP                87327 non-null  int64
 3   COD_REG                87327 non-null  int64
 4   COD_PROV_STORICO       87327 non-null  int64
 5   COD_UTS                87327 non-null  int64
 6   PRO_COM_T              87327 non-null  int64
 7   PRO_COM                87327 non-null  int64
 8   COMUNE                 87316 non-null  str
 9   COMUNE_A               1361 non-null   str
 10  SIGLA_AUTOMOBILISTICA  86315 non-null  str
 11  POP_LEG                87327 non-null  int64
 12  ANNO_CENSIMENTO        87327 non-null  int64
 13  AREA_KMQ               87327 non-null  str
 14  ANNO_AREA              87327 non-null  int64
 15  POP_RES                87327 non-null  int64
 16  ANNO_POP_RES           87327 non-null  int64
 17  anno_riferimento       87327 non-null  int64
dtypes: int64(14), str(4)
memory usage: 12.0 MB

In [11]:
#LAVORO SU UN DATASET DI LAVORO DIFFERENTE DALLA SORGENTE
df_comuni_EDA = df_comuni.copy()

In [12]:
df_comuni_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_PROV_STORICO,COD_UTS,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,SIGLA_AUTOMOBILISTICA,POP_LEG,ANNO_CENSIMENTO,AREA_KMQ,ANNO_AREA,POP_RES,ANNO_POP_RES,anno_riferimento
0,0,0,1,1,1,201,1001,1001,Agliè,NaN,TO,2644,2011,"13,1462",2015,2701,2014,2015
1,1,1,1,1,1,201,1002,1002,Airasca,NaN,TO,3819,2011,"15,7393",2015,3798,2014,2015

In [13]:
# MI CONSERVO SOLO LE COLONNE CHE HO INDICATO DI INTERESSE
# Attenzione rimuovo anche il campo COD_RIP perchè lo prendo da COD_REG - UNA REGIONE PUò APPARTENERE 
# A UNA SOLO COD_RISP E QUINDI COD_RISP NON è LEGATO AL COMUNE
df_comuni_EDA = df_comuni_EDA[['anno_riferimento','COD_REG', 'COD_UTS', 'PRO_COM', 'COMUNE','AREA_KMQ','POP_RES']]

In [14]:
df_comuni_EDA['COD_REG'].unique()

array([ 1,  2,  7,  3,  4,  5,  6,  8, 11,  9, 10, 12, 15, 13, 14, 16, 17,
       18, 19, 20])

In [15]:
df_comuni_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 87327 entries, 0 to 87326
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  87327 non-null  int64
 1   COD_REG           87327 non-null  int64
 2   COD_UTS           87327 non-null  int64
 3   PRO_COM           87327 non-null  int64
 4   COMUNE            87316 non-null  str
 5   AREA_KMQ          87327 non-null  str
 6   POP_RES           87327 non-null  int64
dtypes: int64(5), str(2)
memory usage: 4.7 MB

In [ ]:
# a) tipo dato corretto eccetto area kmq
# b) non sono presenti colonne nulle eccetto su comune desc

In [19]:
# indago su comune

df_comuni_EDA[df_comuni_EDA['COMUNE'].isna()].count()

anno_riferimento    11
COD_REG             11
COD_UTS             11
PRO_COM             11
COMUNE               0
AREA_KMQ            11
POP_RES             11
dtype: int64

In [20]:
df_comuni_EDA[df_comuni_EDA['COMUNE'].isna()]['PRO_COM']
#PROBLEMA SOLO SUL COMUNE 1168 --> verifico sul set di dati degli incidenti
# IN TUTTI GLI ANNI E' VUOTO, FORSE UN VECCHIO COMUNE

167      1168
8215     1168
16218    1168
24201    1168
32158    1168
40084    1168
47988    1168
55891    1168
63795    1168
71696    1168
79595    1168
Name: PRO_COM, dtype: int64

In [25]:
# nr di casi da bonificare
df_comuni_EDA[df_comuni_EDA['COMUNE'].isna()]['PRO_COM'].count()

np.int64(11)

In [26]:
# nr casi non vuoti
df_comuni_EDA[~df_comuni_EDA['COMUNE'].isna()]['PRO_COM'].count()

np.int64(87316)

In [27]:
# totale record
df_comuni_EDA['PRO_COM'].count()
# totale = alla somma dei singoli casi contati prima

np.int64(87327)

In [28]:
# rimuovo i casi vuoiti , stessi in tutti i record 
df_comuni_EDA = df_comuni_EDA[~df_comuni_EDA['COMUNE'].isna()]

In [29]:
# totale record ripulito che deve essere uguale a quello non vuoto prima dell'unione
df_comuni_EDA['PRO_COM'].count()
# ok

np.int64(87316)

In [32]:
df_comuni_EDA["AREA_KMQ"].to_dict()

{0: '13,1462',
 1: '15,7393',
 2: '46,3315',
 3: '11,7314',
 4: '7,3796',
 5: '17,8756',
 6: '5,6261',
 7: '11,9193',
 8: '7,486',
 9: '9,3085',
 10: '38,8782',
 11: '8,1668',
 12: '23,2172',
 13: '9,9605',
 14: '7,0859',
 15: '13,0063',
 16: '4,5064',
 17: '15,4054',
 18: '62,7105',
 19: '2,0289',
 20: '12,8027',
 21: '132,203',
 22: '3,9864',
 23: '6,7343',
 24: '18,5979',
 25: '94,0819',
 26: '14,2234',
 27: '14,3261',
 28: '6,9648',
 29: '13,4189',
 30: '12,3712',
 31: '4,9617',
 32: '10,919',
 33: '6,2914',
 34: '22,7585',
 35: '11,135',
 36: '8,9504',
 37: '5,5701',
 38: '14,3592',
 39: '12,5598',
 40: '14,6868',
 41: '5,476',
 42: '5,0591',
 43: '37,0661',
 44: '8,0973',
 45: '10,2312',
 46: '39,4925',
 47: '14,1314',
 48: '11,0863',
 49: '9,1318',
 50: '11,8499',
 51: '11,9505',
 52: '11,1953',
 53: '23,0319',
 54: '16,4078',
 55: '11,5371',
 56: '10,2579',
 57: '50,679',
 58: '95,7148',
 59: '20,125',
 60: '2,1726',
 61: '14,3136',
 62: '28,7115',
 63: '11,4732',
 64: '17,2796',
 65: '38,7063',
 66: '28,3756',
 67: '14,1345',
 68: '12,3285',
 69: '48,9591',
 70: '13,1595',
 71: '28,0516',
 72: '99,8147',
 73: '121,7001',
 74: '35,4478',
 75: '18,6134',
 76: '12,0221',
 77: '54,1975',
 78: '4,1189',
 79: '26,7549',
 80: '5,9165',
 81: '51,2378',
 82: '3,1638',
 83: '4,9345',
 84: '6,1962',
 85: '17,7329',
 86: '2,6872',
 87: '27,8788',
 88: '56,5727',
 89: '18,0993',
 90: '6,3321',
 91: '4,5894',
 92: '71,1131',
 93: '41,4914',
 94: '3,2384',
 95: '6,8709',
 96: '60,7335',
 97: '19,3134',
 98: '27,5395',
 99: '46,5474',
 100: '14,8499',
 101: '7,8931',
 102: '49,4091',
 103: '12,0415',
 104: '4,3457',
 105: '15,6427',
 106: '16,5003',
 107: '24,8185',
 108: '10,9482',
 109: '20,1488',
 110: '7,4018',
 111: '20,5108',
 112: '14,4442',
 113: '33,3833',
 114: '71,7376',
 115: '12,8199',
 116: '18,987',
 117: '92,0935',
 118: '4,3296',
 119: '13,1321',
 120: '14,7506',
 121: '8,0292',
 122: '4,7716',
 123: '5,5042',
 124: '30,1075',
 125: '12,0353',
 126: '12,7929',
 127: '10,2876',
 128: '14,29',
 129: '32,4355',
 130: '45,6753',
 131: '7,9366',
 132: '5,3912',
 133: '132,5173',
 134: '12,7158',
 135: '7,2096',
 136: '4,1914',
 137: '4,8835',
 138: '17,7414',
 139: '7,0398',
 140: '5,2585',
 141: '14,1404',
 142: '6,3129',
 143: '11,2593',
 144: '38,2587',
 145: '7,0706',
 146: '28,6942',
 147: '27,3424',
 148: '16,5439',
 149: '12,6383',
 150: '4,442',
 151: '29,0871',
 152: '4,0825',
 153: '30,3332',
 154: '17,6554',
 155: '47,5288',
 156: '4,5007',
 157: '4,6567',
 158: '6,4681',
 159: '7,3567',
 160: '20,9036',
 161: '7,3896',
 162: '6,4895',
 163: '20,5627',
 164: '78,0481',
 165: '11,353',
 166: '3,0743',
 168: '28,5542',
 169: '6,303',
 170: '22,2078',
 171: '7,1541',
 172: '5,4885',
 173: '4,5771',
 174: '99,7857',
 175: '5,4058',
 176: '5,0819',
 177: '15,8878',
 178: '2,6886',
 179: '4,4056',
 180: '11,54',
 181: '1,568',
 182: '9,173',
 183: '26,0906',
 184: '4,708',
 185: '63,183',
 186: '4,0041',
 187: '5,3498',
 188: '16,4634',
 189: '34,7183',
 190: '50,3376',
 191: '21,8196',
 192: '19,6488',
 193: '40,1459',
 194: '9,9034',
 195: '11,0343',
 196: '75,6186',
 197: '8,5611',
 198: '19,0609',
 199: '4,4476',
 200: '89,2017',
 201: '72,6092',
 202: '29,8455',
 203: '22,4785',
 204: '10,5052',
 205: '6,2419',
 206: '7,8803',
 207: '2,038',
 208: '3,9559',
 209: '17,7879',
 210: '6,6658',
 211: '43,6002',
 212: '10,8334',
 213: '25,1076',
 214: '35,8318',
 215: '12,5838',
 216: '32,2459',
 217: '10,8733',
 218: '29,4998',
 219: '8,5756',
 220: '14,1912',
 221: '9,7039',
 222: '11,2106',
 223: '96,2686',
 224: '10,6877',
 225: '12,4075',
 226: '59,3732',
 227: '9,065',
 228: '26,9371',
 229: '15,1002',
 230: '4,9519',
 231: '38,3198',
 232: '2,1034',
 233: '15,8859',
 234: '2,433',
 235: '22,2318',
 236: '20,9068',
 237: '3,3809',
 238: '3,3037',
 239: '14,9796',
 240: '6,6513',
 241: '15,8616',
 242: '8,8866',
 243: '20,4049',
 244: '19,7366',
 245: '9,6132',
 246: '9,7933',
 247: '17,3442',
 248: '12,5517',
 249: '12,4446',
 250: '2,1243',
 251: '11,152',
 252: '16,5766',
 253: '12,5719',
 254: '8,3683',
 255: '9,7945',
 256: '16,1983',
 257: '78,2772',
 258: '17,3112',
 259: '31,6768',
 260: '8,0308',
 261: '11,3557',
 262: '25,9158',
 263: '6,0578',
 264: '32,366',
 265: '23,2604',
 266: '29,6785',
 267: '2,214',
 268: '22,4686',
 269: '10,9879',
 270: '8,6751',
 271: '130,0091',
 272: '9,8238',
 273: '5,4545',
 274: '21,0981',
 275: '16,4059',
 276: '12,2462',
 277: '39,3597',
 278: '10,4544',
 279: '12,3475',
 280: '37,9669',
 281: '98,5375',
 282: '7,2292',
 283: '36,5253',
 284: '9,12',
 285: '6,0792',
 286: '11,9094',
 287: '71,8527',
 288: '22,5579',
 289: '7,0929',
 290: '19,1435',
 291: '20,4424',
 292: '29,4882',
 293: '31,9431',
 294: '12,0691',
 295: '4,6453',
 296: '32,9363',
 297: '2,9677',
 298: '41,1543',
 299: '50,7854',
 300: '4,0306',
 301: '10,4088',
 302: '5,7067',
 303: '11,4091',
 304: '25,6868',
 305: '60,2927',
 306: '11,4228',
 307: '19,8767',
 308: '17,6941',
 309: '14,0573',
 310: '17,0748',
 311: '4,6817',
 312: '84,1119',
 313: '32,4629',
 314: '20,9827',
 315: '72,0383',
 316: '13,7804',
 317: '24,565',
 318: '23,3101',
 319: '26,3156',
 320: '9,7885',
 321: '16,8079',
 322: '41,8058',
 323: '33,8706',
 324: '39,5707',
 325: '41,0901',
 326: '19,2949',
 327: '7,2305',
 328: '25,0776',
 329: '34,1364',
 330: '22,8004',
 331: '24,1087',
 332: '11,0218',
 333: '30,1062',
 334: '16,205',
 335: '9,6044',
 336: '10,0488',
 337: '9,538',
 338: '25,3078',
 339: '7,3878',
 340: '9,2234',
 341: '20,9676',
 342: '34,8563',
 343: '48,2233',
 344: '14,0162',
 345: '16,4768',
 346: '28,1403',
 347: '23,2424',
 348: '16,7629',
 349: '33,6659',
 350: '12,503',
 351: '11,8817',
 352: '6,0875',
 353: '9,644',
 354: '18,9701',
 355: '22,574',
 356: '58,028',
 357: '6,6672',
 358: '13,9178',
 359: '20,1818',
 360: '11,715',
 361: '16,5035',
 362: '6,527',
 363: '13,9396',
 364: '8,2949',
 365: '17,3517',
 366: '8,6903',
 367: '13,5976',
 368: '16,1782',
 369: '11,5388',
 370: '16,156',
 371: '10,9022',
 372: '43,2698',
 373: '36,0226',
 374: '24,3032',
 375: '26,2702',
 376: '61,1321',
 377: '9,4089',
 378: '27,916',
 379: '24,4754',
 380: '11,8379',
 381: '29,2681',
 382: '14,8536',
 383: '12,1875',
 384: '8,7766',
 385: '31,5982',
 386: '30,6327',
 387: '53,1294',
 388: '22,5335',
 389: '18,2544',
 390: '20,9053',
 391: '18,314',
 392: '12,2491',
 393: '70,6054',
 394: '44,7508',
 395: '28,4259',
 396: '88,1193',
 397: '79,7743',
 398: '25,5109',
 399: '14,5822',
 400: '20,2573',
 401: '14,5364',
 402: '9,9965',
 403: '31,5154',
 404: '15,1698',
 405: '19,4928',
 406: '39,1786',
 407: '12,4536',
 408: '9,608',
 409: '8,5097',
 410: '3,3043',
 411: '21,0913',
 412: '32,2699',
 413: '13,3738',
 414: '4,7479',
 415: '24,7562',
 416: '22,3213',
 417: '39,985',
 418: '14,6557',
 419: '16,0407',
 420: '10,531',
 421: '39,4901',
 422: '17,4849',
 423: '10,7918',
 424: '14,6411',
 425: '6,4855',
 426: '9,8335',
 427: '8,3261',
 428: '32,6332',
 429: '3,1618',
 430: '4,4493',
 431: '7,1035',
 432: '8,5068',
 433: '5,0977',
 434: '7,2522',
 435: '9,2147',
 436: '21,1702',
 437: '29,3662',
 438: '10,0494',
 439: '3,7542',
 440: '16,2884',
 441: '20,6442',
 442: '12,5821',
 443: '19,5208',
 444: '14,3337',
 445: '17,3717',
 446: '7,2834',
 447: '13,5806',
 448: '10,6587',
 449: '5,8541',
 450: '7,7879',
 451: '6,8639',
 452: '7,5349',
 453: '7,7187',
 454: '5,521',
 455: '23,5907',
 456: '8,2651',
 457: '11,3421',
 458: '103,0492',
 459: '37,7943',
 460: '5,9351',
 461: '6,65',
 462: '5,2272',
 463: '8,1345',
 464: '7,0713',
 465: '2,7659',
 466: '9,8653',
 467: '12,2966',
 468: '12,126',
 469: '8,8526',
 470: '17,9764',
 471: '17,6906',
 472: '8,5099',
 473: '11,4512',
 474: '34,8992',
 475: '9,5352',
 476: '10,7543',
 477: '6,3719',
 478: '12,9144',
 479: '21,3271',
 480: '8,4632',
 481: '13,2408',
 482: '38,2224',
 483: '10,0123',
 484: '13,612',
 485: '9,8717',
 486: '17,7798',
 487: '13,2939',
 488: '15,4636',
 489: '151,5276',
 490: '36,9173',
 491: '53,5853',
 492: '4,5899',
 493: '7,4616',
 494: '76,2591',
 495: '4,9174',
 496: '30,949',
 497: '63,2505',
 498: '15,3257',
 499: '7,7637',
 500: '81,9923',
 501: '5,6892',
 502: '12,0006',
 503: '11,1195',
 504: '17,6865',
 505: '62,07',
 506: '5,003',
 507: '48,9673',
 508: '5,4389',
 509: '3,1118',
 510: '25,8445',
 511: '7,2409',
 512: '8,4778',
 513: '22,3397',
 514: '5,5405',
 515: '14,5453',
 516: '50,9483',
 517: '59,5298',
 518: '6,2376',
 519: '52,1796',
 520: '10,124',
 521: '28,0639',
 522: '65,8443',
 523: '23,6378',
 524: '3,6114',
 525: '17,8655',
 526: '48,4476',
 527: '11,5018',
 528: '41,6759',
 529: '26,3287',
 530: '19,3047',
 531: '25,838',
 532: '6,4192',
 533: '17,8066',
 534: '7,1148',
 535: '33,9513',
 536: '3,3404',
 537: '17,1301',
 538: '14,8584',
 539: '7,8028',
 540: '11,5178',
 541: '49,307',
 542: '6,2621',
 543: '4,7202',
 544: '11,6345',
 545: '15,5227',
 546: '16,4378',
 547: '51,5946',
 548: '31,1052',
 549: '42,4848',
 550: '37,0496',
 551: '10,1423',
 552: '18,2419',
 553: '18,5961',
 554: '43,1656',
 555: '81,5351',
 556: '95,0188',
 557: '6,1219',
 558: '5,9034',
 559: '17,1508',
 560: '10,0878',
 561: '24,9874',
 562: '20,5398',
 563: '15,3423',
 564: '8,1183',
 565: '52,0529',
 566: '119,6691',
 567: '127,3063',
 568: '17,5432',
 569: '35,6829',
 570: '58,9574',
 571: '26,2196',
 572: '160,7314',
 573: '24,9305',
 574: '16,4418',
 575: '7,03',
 576: '7,6666',
 577: '130,1434',
 578: '47,1437',
 579: '37,6433',
 580: '17,0106',
 581: '4,9691',
 582: '5,7412',
 583: '131,281',
 584: '13,7224',
 585: '13,9699',
 586: '13,6769',
 587: '18,9108',
 588: '3,8082',
 589: '13,4459',
 590: '3,4042',
 591: '5,0784',
 592: '17,7124',
 593: '24,1658',
 594: '11,8291',
 595: '12,2004',
 596: '14,2414',
 597: '15,739',
 598: '70,8104',
 599: '8,2287',
 600: '24,6562',
 601: '9,5',
 602: '33,2204',
 603: '20,031',
 604: '11,7345',
 605: '28,9869',
 606: '11,3762',
 607: '41,1258',
 608: '13,0258',
 609: '13,2806',
 610: '27,9056',
 611: '15,0682',
 612: '20,5111',
 613: '17,3498',
 614: '17,4382',
 615: '7,6796',
 616: '14,9114',
 617: '4,9903',
 618: '87,0516',
 619: '12,933',
 620: '25,2745',
 621: '26,8203',
 622: '23,5797',
 623: '11,8403',
 624: '11,6271',
 625: '6,4303',
 626: '11,1041',
 627: '42,2211',
 628: '24,6999',
 629: '6,9363',
 630: '10,2358',
 631: '23,9934',
 632: '22,1919',
 633: '27,6758',
 634: '17,3282',
 635: '26,1826',
 636: '21,3028',
 637: '7,9261',
 638: '11,5183',
 639: '15,707',
 640: '11,7055',
 641: '7,8083',
 642: '47,3592',
 643: '124,4931',
 644: '14,0873',
 645: '58,2693',
 646: '8,6797',
 647: '34,5115',
 648: '12,4249',
 649: '9,8932',
 650: '10,2155',
 651: '67,9186',
 652: '26,5691',
 653: '15,3103',
 654: '10,6214',
 655: '55,1856',
 656: '4,0347',
 657: '14,3043',
 658: '17,4774',
 659: '10,3146',
 660: '94,9229',
 661: '19,2934',
 662: '52,3851',
 663: '20,0092',
 664: '9,0306',
 665: '27,3754',
 666: '14,3615',
 667: '48,0562',
 668: '52,47',
 669: '6,8436',
 670: '11,352',
 671: '23,8368',
 672: '6,4212',
 673: '25,0038',
 674: '29,8104',
 675: '24,2989',
 676: '7,0152',
 677: '26,4023',
 678: '84,6105',
 679: '11,2407',
 680: '19,1492',
 681: '4,5076',
 682: '9,353',
 683: '10,5849',
 684: '8,9004',
 685: '19,9166',
 686: '7,5091',
 687: '10,5052',
 688: '8,0742',
 689: '24,3254',
 690: '12,696',
 691: '76,5902',
 692: '46,1392',
 693: '98,9069',
 694: '4,8454',
 695: '54,2618',
 696: '15,504',
 697: '39,7088',
 698: '18,1119',
 699: '27,4544',
 700: '10,0758',
 701: '23,5722',
 702: '13,1142',
 703: '110,7876',
 704: '9,3878',
 705: '30,4979',
 706: '8,3908',
 707: '8,8995',
 708: '8,6012',
 709: '11,6848',
 710: '35,4155',
 711: '17,0935',
 712: '28,0956',
 713: '12,2016',
 714: '7,1829',
 715: '18,5376',
 716: '5,3901',
 717: '3,8226',
 718: '9,5956',
 719: '10,5253',
 720: '28,3367',
 721: '153,3126',
 722: '23,1017',
 723: '16,9559',
 724: '10,92',
 725: '20,3938',
 726: '7,1571',
 727: '62,0563',
 728: '26,132',
 729: '14,0688',
 730: '25,7363',
 731: '7,9417',
 732: '29,7324',
 733: '28,2878',
 734: '14,7884',
 735: '19,4958',
 736: '183,1692',
 737: '21,0672',
 738: '8,09',
 739: '15,4485',
 740: '9,5399',
 741: '10,8608',
 742: '11,4124',
 743: '151,3113',
 744: '6,4341',
 745: '5,066',
 746: '5,2796',
 747: '7,343',
 748: '8,9008',
 749: '15,7621',
 750: '19,1608',
 751: '12,7884',
 752: '17,2931',
 753: '15,7149',
 754: '6,8923',
 755: '23,4326',
 756: '9,7214',
 757: '5,0565',
 758: '12,648',
 759: '11,8391',
 760: '21,5648',
 761: '17,3374',
 762: '11,8622',
 763: '20,0881',
 764: '4,2882',
 765: '3,0662',
 766: '23,1785',
 767: '9,5499',
 768: '8,2039',
 769: '21,6068',
 770: '5,6273',
 771: '10,8477',
 772: '5,5928',
 773: '3,9384',
 774: '4,6529',
 775: '11,7779',
 776: '2,417',
 777: '5,5045',
 778: '10,7326',
 779: '4,0489',
 780: '16,5226',
 781: '5,0824',
 782: '5,0231',
 783: '4,4766',
 784: '10,3333',
 785: '8,4254',
 786: '5,3987',
 787: '36,9432',
 788: '6,7531',
 789: '11,9251',
 790: '13,927',
 791: '8,13',
 792: '7,2168',
 793: '5,8883',
 794: '10,4721',
 795: '20,7037',
 796: '13,5026',
 797: '14,8219',
 798: '4,3739',
 799: '4,9251',
 800: '4,1551',
 801: '11,9588',
 802: '22,3971',
 803: '14,2321',
 804: '9,1104',
 805: '14,2057',
 806: '17,421',
 807: '14,3291',
 808: '6,855',
 809: '8,5373',
 810: '14,497',
 811: '6,6348',
 812: '10,1408',
 813: '15,4192',
 814: '16,0976',
 815: '5,4053',
 816: '30,3632',
 817: '5,617',
 818: '12,026',
 819: '9,563',
 820: '9,0013',
 821: '4,082',
 822: '11,0244',
 823: '11,0036',
 824: '2,8582',
 825: '13,2049',
 826: '8,835',
 827: '6,4171',
 828: '12,1805',
 829: '12,5631',
 830: '29,9827',
 831: '7,8377',
 832: '15,9109',
 833: '47,8656',
 834: '6,1477',
 835: '7,2094',
 836: '9,6838',
 837: '11,8691',
 838: '5,3426',
 839: '12,3285',
 840: '8,4471',
 841: '6,6804',
 842: '3,28',
 843: '16,1173',
 844: '11,7833',
 845: '5,5952',
 846: '4,7599',
 847: '22,0383',
 848: '13,1655',
 849: '3,9754',
 850: '13,6219',
 851: '6,653',
 852: '12,8798',
 853: '41,948',
 854: '6,1268',
 855: '9,2863',
 856: '26,8624',
 857: '33,2967',
 858: '21,2298',
 859: '203,5657',
 860: '13,1588',
 861: '12,2135',
 862: '9,1382',
 863: '11,328',
 864: '2,1269',
 865: '29,2434',
 866: '12,2375',
 867: '16,6197',
 868: '15,0526',
 869: '28,7122',
 870: '8,3258',
 871: '13,4397',
 872: '2,8874',
 873: '17,5936',
 874: '39,3977',
 875: '6,6034',
 876: '9,723',
 877: '44,5297',
 878: '67,6133',
 879: '9,0235',
 880: '17,5285',
 881: '46,6332',
 882: '9,2493',
 883: '18,4376',
 884: '24,0619',
 885: '28,4663',
 886: '5,0526',
 887: '9,7892',
 888: '10,4833',
 889: '13,3394',
 890: '55,2555',
 891: '6,9232',
 892: '16,3412',
 893: '12,1635',
 894: '12,0104',
 895: '86,2097',
 896: '12,9866',
 897: '9,0373',
 898: '13,8466',
 899: '33,0925',
 900: '23,7721',
 901: '7,2089',
 902: '2,4828',
 903: '45,1283',
 904: '4,66',
 905: '13,977',
 906: '11,5908',
 907: '9,5776',
 908: '13,1107',
 909: '45,4213',
 910: '5,4872',
 911: '10,4466',
 912: '5,5524',
 913: '10,4427',
 914: '4,747',
 915: '17,3008',
 916: '10,3002',
 917: '11,6117',
 918: '7,8996',
 919: '14,3874',
 920: '5,2191',
 921: '7,4621',
 922: '18,2763',
 923: '53,8484',
 924: '25,0138',
 925: '17,6161',
 926: '7,7515',
 927: '5,2861',
 928: '8,431',
 929: '29,5609',
 930: '6,9336',
 931: '27,0575',
 932: '25,5333',
 933: '17,7684',
 934: '12,1543',
 935: '20,7165',
 936: '3,2797',
 937: '45,0432',
 938: '5,4494',
 939: '17,3842',
 940: '9,0802',
 941: '25,9429',
 942: '2,8021',
 943: '23,5483',
 944: '14,5358',
 945: '21,8759',
 946: '9,035',
 947: '22,2319',
 948: '19,7375',
 949: '9,1998',
 950: '13,2357',
 951: '32,504',
 952: '2,7527',
 953: '19,6941',
 954: '8,54',
 955: '6,5185',
 956: '29,0329',
 957: '9,6176',
 958: '23,7473',
 959: '5,3756',
 960: '5,7241',
 961: '7,4867',
 962: '17,5982',
 963: '5,4513',
 964: '9,8515',
 965: '17,7049',
 966: '23,9524',
 967: '13,2197',
 968: '10,2943',
 969: '15,3104',
 970: '55,1948',
 971: '22,4629',
 972: '15,4279',
 973: '7,5707',
 974: '2,6908',
 975: '5,0996',
 976: '14,5434',
 977: '35,3724',
 978: '27,3665',
 979: '15,1834',
 980: '4,4198',
 981: '41,7376',
 982: '12,5365',
 983: '5,2811',
 984: '11,3546',
 985: '7,9973',
 986: '15,6455',
 987: '13,4427',
 988: '29,7041',
 989: '18,9177',
 990: '11,9679',
 991: '11,6495',
 992: '69,0281',
 993: '14,0866',
 994: '36,1765',
 995: '5,9724',
 996: '33,0071',
 997: '36,1651',
 998: '17,7338',
 999: '10,5153',
 1000: '10,0516',
 ...}

In [36]:
#test di conversione
df_comuni_EDA["AREA_KMQ"].str.replace(',', '.').astype('float')

0         13.1462
1         15.7393
2         46.3315
3         11.7314
4          7.3796
           ...
87322    181.3947
87323    130.3596
87324     58.1781
87325     86.8137
87326     27.1943
Name: AREA_KMQ, Length: 87316, dtype: float64

In [ ]:
# sostituzione dato
df_comuni_EDA["AREA_KMQ"] = df_comuni_EDA["AREA_KMQ"].str.replace(',', '.')

In [49]:
#converto
df_comuni_EDA["AREA_KMQ"] = df_comuni_EDA.AREA_KMQ.astype(float)

In [50]:
#verifico
df_comuni_EDA["AREA_KMQ"].info()

<class 'pandas.Series'>
Index: 87316 entries, 0 to 87326
Series name: AREA_KMQ
Non-Null Count  Dtype
--------------  -----
87316 non-null  float64
dtypes: float64(1)
memory usage: 1.3 MB

In [58]:
df_comuni_EDA.info()

<class 'pandas.DataFrame'>
Index: 87316 entries, 0 to 87326
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  87316 non-null  int64
 1   COD_REG           87316 non-null  int64
 2   COD_UTS           87316 non-null  int64
 3   PRO_COM           87316 non-null  int64
 4   COMUNE            87316 non-null  str
 5   AREA_KMQ          87316 non-null  float64
 6   POP_RES           87316 non-null  int64
dtypes: float64(1), int64(5), str(1)
memory usage: 5.3 MB

In [59]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_comuni_EDA, f"ElencoComuni",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuni.csv