In [1]:
import numpy as np
import pandas as pd

In [2]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [3]:
df_incidenti_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoIncidenti.csv")

In [4]:
df_comuni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoComuni.csv")

In [5]:
df_regioni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRegioni.csv")

In [6]:
df_ripgeo_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRipartizioniGeografiche.csv")

In [7]:
df_regioni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG'], dtype='str')

In [8]:
df_ripgeo_an.columns

Index(['Unnamed: 0', 'COD_RIP', 'DEN_RIP'], dtype='str')

In [9]:
#merge tra regioni e ripartizione geografica
# la chiave di relazione è COD_RIP per ambedue le tb
df_reg_ripgeo_merge = df_regioni_an.merge(df_ripgeo_an[['COD_RIP','DEN_RIP']],
                                            how='inner', 
                                            left_on='COD_RIP', 
                                            right_on='COD_RIP')

In [10]:
df_reg_ripgeo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG',
       'DEN_RIP'],
      dtype='str')

In [11]:
df_reg_ripgeo_merge.head(3)

,Unnamed: 0,anno_riferimento,COD_RIP,COD_REG,DEN_REG,DEN_RIP
0,0,2015,1,1,Piemonte,Nord-ovest
1,1,2015,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest
2,2,2015,1,3,Lombardia,Nord-ovest

In [12]:
nr_rec_reg = df_regioni_an.COD_REG.count()
nr_rec_merge_reg = df_reg_ripgeo_merge.COD_REG.count()
print(f'Sorgente: {nr_rec_reg} - Mege: {nr_rec_merge_reg}')

Sorgente: 220 - Mege: 220

In [13]:
df_comuni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'PRO_COM',
       'COMUNE', 'AREA_KMQ', 'POP_RES'],
      dtype='str')

In [14]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è COD_REG per ambedue le tb
df_com_reg_geo_merge = df_comuni_an.merge(df_reg_ripgeo_merge[['anno_riferimento', 'COD_REG', 'DEN_REG','COD_RIP','DEN_RIP']],
                                            how='inner', 
                                            left_on=['anno_riferimento','COD_REG'], 
                                            right_on=['anno_riferimento','COD_REG'])

In [15]:
df_com_reg_geo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'PRO_COM',
       'COMUNE', 'AREA_KMQ', 'POP_RES', 'DEN_REG', 'COD_RIP', 'DEN_RIP'],
      dtype='str')

In [16]:
nr_rec_com = df_comuni_an.PRO_COM.count()
nr_rec_merge_com = df_com_reg_geo_merge.PRO_COM.count()
print(f'Sorgente: {nr_rec_com} - Mege: {nr_rec_merge_com}')

Sorgente: 87316 - Mege: 87316

In [17]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_com_reg_geo_merge, f"ElencoComuniRegioniRipGeografiche",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniRegioniRipGeografiche.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniRegioniRipGeografiche.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniRegioniRipGeografiche.csv

In [18]:
df_incidenti_an.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'REF_AREA', 'RESULT', 'TIME_PERIOD',
       'OBS_VALUE', 'RESULT_DESC'],
      dtype='str')

In [19]:
df_com_reg_geo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'PRO_COM',
       'COMUNE', 'AREA_KMQ', 'POP_RES', 'DEN_REG', 'COD_RIP', 'DEN_RIP'],
      dtype='str')

In [22]:
df_incidenti_an.TIME_PERIOD.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [24]:
df_incidenti_an.REF_AREA.unique

<bound method Series.unique of 0           1001
1           1001
2           1001
3           1001
4           1001
           ...
382363    111107
382364    111107
382365    111107
382366    111107
382367    111107
Name: REF_AREA, Length: 382368, dtype: int64>

In [25]:
df_com_reg_geo_merge.COD_UTS.unique()

array([201,   2,   3,   4,   5,   6,   7,   8,   9, 210,  11,  12,  13,
        14, 215,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
       227,  28,  29,  30,  31,  32,  33,  34,  35,  36, 237,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47, 248,  49,  50,  51,  52,
        53,  54,  55,  56,  57, 258,  59,  60,  61,  62, 263,  64,  65,
        66,  67,  68,  69,  70,  71, 272,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 280, 282, 283, 287, 292, 111])

In [20]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è COD_REG per ambedue le tb
#df_incidente_flat = 
df_incidenti_an.merge(df_com_reg_geo_merge[['anno_riferimento',
                                                    'COD_UTS', 'PRO_COM', 'COMUNE',
                                                    'COD_REG', 'DEN_REG',
                                                    'COD_RIP','DEN_RIP',
                                                    'AREA_KMQ', 'POP_RES']],
                                            how='inner', 
                                            left_on=['TIME_PERIOD','REF_AREA'], 
                                            right_on=['anno_riferimento','COD_UTS'])

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, REF_AREA, RESULT, TIME_PERIOD, OBS_VALUE, RESULT_DESC, anno_riferimento, COD_UTS, PRO_COM, COMUNE, COD_REG, DEN_REG, COD_RIP, DEN_RIP, AREA_KMQ, POP_RES]
Index: []